apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cp4ba-cr
  namespace: default
rules:
  - verbs:
      - '*'
    apiGroups:
      - config.openshift.io/v1
      - operator.openshift.io/v1
    resources:
      - ingresscontrollers
      - ingress
  - verbs:
      - '*'
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - get
      - watch
      - list
      - create
      - patch
      - delete
    apiGroups:
      - ''
    resources:
      - secrets
      - projects
      - namespaces
      - routes
      - pods
      - pods/exec
  - verbs:
      - get
      - watch
      - list
      - create
      - patch
    apiGroups:
      - icp4a.ibm.com
    resources:
      - icp4aclusters

