kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openldap-configure-cr
rules:
- apiGroups: [""] 
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""] 
  resources: ["configmaps"]
  verbs: ["create", "list", "get", "delete"]
- apiGroups: [""] 
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: ["batch"] 
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
