apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: global-ca-cr
  namespace: default
rules:
  - apiGroups:
      - 'config.openshift.io/v1'
    resources:
      - ingresscontroller
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - watch
      - list
      - patch
      - create

